########
# user #
########

user_name: qualif


########
# time #
########

timezone: 'Europe/Paris'


############
# streamer #
############

stream_manager_database_ip: localhost
stream_manager_database_name: MyTVTools
stream_manager_database_user: test
stream_manager_database_password: univers
stream_manager_admin_password: papsm
stream_manager_manager_password: mppsq
stream_manager_tar_name: streammanager-1.3-SNAPSHOT.tar.gz

multicat_supervisor_ip: localhost
multicat_supervisor_ssh_login: qualif
multicat_supervisor_ssh_password: qualif
multicat_supervisor_network_ttl: 0


#################
# junit-history #
#################

junit_history_database_ip: localhost
junit_history_database_name: JUnitHistoryTools
junit_history_database_user: test
junit_history_database_password: univers
junit_history_admin_password: papsm
junit_history_manager_password: mppsq
junit_history_tar_name: junithistory-1.3-SNAPSHOT.tar.gz


#########
# maven #
#########

maven_artifact_command: "mvn install:install-file -Dfile=org.moxieapps.gwt.uploader-1.1.0.jar -DgroupId=org.moxieapps -DartifactId=org.moxieapps.gwt.uploader -Dversion=1.1.0 -Dpackaging=jar -DgeneratePom=true"
maven_packaging_command: "mvn clean package"


#######
# gwt #
#######

gwt_uploader_library_url: http://sourceforge.net/projects/gwt-uploader/files/1.1.0/org.moxieapps.gwt.uploader-1.1.0.jar


#######
# nas #
#######

nas_src: 10.185.110.178:/volume1/NetBackup/


#######
# ntp #
#######

# List of ntp servers
ntp_servers:
  - { server: "server sfebua31.bagnolet.francetelecom.fr iburst #FT-NTP-Server" }
  - { server: "server OPADYX41.rouen.francetelecom.fr iburst #FT-NTP-Server" }
  - { server: "server OPADYV21.nanterre.francetelecom.fr iburst #FT-NTP-Server" }
  - { server: "server sfebuv31.nanterre.francetelecom.fr iburst #FT-NTP-Server" }
  - { server: "server SFEBUS11.strasbourg.francetelecom.fr iburst #FT-NTP-Server" }
  - { server: "server sfebus21.strasbourg.francetelecom.fr iburst #FT-NTP-Server" }
  - { server: "server sfebuf11.lille.francetelecom.fr iburst #FT-NTP-Server" }


#########
# cntlm #
#########

cntlm_username: skwp5790
cntlm_domain: ad.francetelecom.fr

# check cntlm documentation to generate password
cntlm_pass_lm: C104B7E7834BA39ADA5F4423AA8761A5
cntlm_pass_nt: 31E9A4FC4EE14B6BDB129B67876AF24D
cntlm_pass_ntlm: 5B09C6A7F62653ECF9BDA98C37C6810A

cntlm_proxies:
  - { ip: proxy-tls.toulouse.francetelecom.fr, port: 8080 }
  - { ip: proxy, port: 8080 }
  - { ip: proxybkp, port: 8080 }

cntlm_no_proxy: "localhost, 127.0.0.*, 10.*, 192.168.*"

cntlm_listen_address: localhost
cntlm_listen_port: 3128


##############
# standalone #
##############

standalone_url: http://10.192.34.168/jenkins/view/standalone/job/standalone-trunk-all/lastSuccessfulBuild/artifact/target/newtv-standalone-1.0.5-SNAPSHOT-all.zip


###########
# jenkins #
###########

jenkins_init_options: -Dhudson.model.DirectoryBrowserSupport.CSP=
jenkins_init_workaround: '/bin/su - jenkins -c "export DISPLAY=:99 && java -jar /var/lib/jenkins/selenium-server-standalone.jar -port 4499 -singleWindow -userExtensions /var/lib/jenkins/jobs/CHECKOUT_SVN/workspace/selenium/user-extensions.js -htmlSuite *firefox http://localhost /var/lib/jenkins/workaround/init/INIT_JENKINS_TESTSUITE.html /tmp/JENKINS_INIT_result.html"'


###################
# test-dispatcher #
###################

test_dispatcher_port: 8086
test_dispatcher_admin_port: 8081


###########
# network #
###########

qualif_network_address: 10.185.111.250
debug_network_address: 10.185.111.249
network_netmask: 255.255.254.0
network_gateway: 10.185.111.254
network_dns: 10.171.108.2 10.171.36.15 10.171.35.3

