---
# This playbook will configure Orange time

- name: Start the ntp service
  service: >
    name=ntp
    state=started
    enabled=yes
  become: yes

- name: Set local timezone
  copy: >
    content={{ timezone }}
    dest={{ timezone_file }}
  become: yes

- name: Update tzdata
  command: "{{ update_tzdata_command }}"
  become: yes

- name: Remove old ntp servers configuration
  lineinfile: >
    dest={{ ntp_conf_file }}
    regexp="{{ ntp_conf_tag }}"
    state=absent
  become: yes

- name: Setting up ntp servers configuration
  lineinfile: >
    dest={{ ntp_conf_file }}
    line="{{ item.server }}"
    insertafter=EOF
  with_items:
    - "{{ ntp_servers }}"
  become: yes

- name: Restart the ntp service
  service: >
    name=ntp
    state=restarted
    sleep=3
  become: yes
