---

webupd8team_java_key_url: keyserver.ubuntu.com
webupd8team_java_key_id: EEA14886
webupd8team_java_ppa_url: http://ppa.launchpad.net/webupd8team/java/ubuntu
webupd8team_java_list_template: webupd8team-java.list.j2
webupd8team_java_list_path: /etc/apt/sources.list.d/webupd8team-java.list

java_package_name: oracle-java8-installer
java_license_question: "shared/accepted-oracle-license-v1-1"

jenkins_key_url: http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key
jenkins_list_template: jenkins.list.j2
jenkins_list_path: /etc/apt/sources.list.d/jenkins.list
