---

stream_manager_sql: stream-manager.sql
stream_manager_backup_sql_path: /mnt/nas/banc_qualif/home/qualif/Bureau/SAVE_TO_NAS/MyTVTools_dump.SQL

stream_manager_war_path: /var/lib/tomcat8/webapps
stream_manager_war_name: StreamManager.war
stream_manager_xml_path: /var/lib/tomcat8/conf/Catalina/localhost
stream_manager_xml_name: StreamManager.xml
stream_manager_url: https://github.com/orange-tv-blagnac/stream-manager.git
stream_manager_dir_name: stream-manager
stream_manager_path: /usr/local/stream-manager
stream_manager_src_path: /usr/local/stream-manager/src
stream_manager_tests_dir_path: /home/qualif/tests
tomcat_ssh_dir_path: /usr/share/tomcat8/.ssh

multicat_supervisor_path: /usr/local/multicat-tools
multicat_supervisor_src_dir_path: /usr/local/multicat-tools/src

multicat_supervisor_url: https://github.com/orange-tv-blagnac/multicat-supervisor.git
multicat_supervisor_src_path: /usr/local/multicat-tools/src/multicat-supervisor
multicat_supervisor_config_file: multicat.ini
multicat_supervisor_script: /usr/local/multicat-tools/sh/multicat-supervisor.sh
multicat_supervisor_videos_path: /usr/local/multicat-tools/videos
multicat_supervisor_videos_nas_path: /mnt/nas/banc_qualif/usr/local/multicat-tools/videos
multicat_supervisor_service_template: multicat-supervisor.service.j2
multicat_supervisor_service_path: /etc/systemd/system/multicat-supervisor.service
multicat_supervisor_service_name: multicat-supervisor.service

bitstream_url: https://get.videolan.org/bitstream/1.1/bitstream-1.1.tar.bz2
bitstream_archive_name: bitstream-1.1.tar.bz2
bitstream_src_path: /usr/local/multicat-tools/src/bitstream-1.1
