SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `MyTVTools`
--

-- --------------------------------------------------------

--
-- Table structure for table `eit`
--

CREATE TABLE IF NOT EXISTS `eit` (
  `ideit` int(11) NOT NULL,
  `lcn` int(11) DEFAULT '0',
  `usi` int(11) DEFAULT '0',
  `name` varchar(128) DEFAULT NULL,
  `description` varchar(128) DEFAULT NULL,
  `user1` varchar(45) DEFAULT NULL,
  `section_0` mediumtext,
  `section_1` mediumtext,
  `enable` tinyint(4) DEFAULT '0',
  `eit_ts` bigint(20) DEFAULT NULL,
  `videofile` varchar(255) DEFAULT NULL,
  `videoid` int(11) NOT NULL,
  `address` varchar(15) NOT NULL,
  `port` int(11) DEFAULT NULL,
  `tsid` int(11) NOT NULL,
  `sid` int(11) NOT NULL,
  `onid` int(11) NOT NULL,
  `status` varchar(20) DEFAULT 'NEW',
  `lastUpdate` datetime DEFAULT NULL,
  `protected` tinyint(4) NOT NULL DEFAULT '0',
  `to_inject` tinyint(4) NOT NULL DEFAULT '1'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `eit`
--

INSERT INTO `eit` (`ideit`, `lcn`, `usi`, `name`, `description`, `user1`, `section_0`, `section_1`, `enable`, `eit_ts`, `videofile`, `videoid`, `address`, `port`, `tsid`, `sid`, `onid`, `status`, `lastUpdate`, `protected`, `to_inject`) VALUES
(1, 802, 2518, 'HD CSA 2 & TNT', 'Flux banc qualif', 'Banc qualif', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"IP SD Noir Blanc","event_text":"IP SD Noir Blanc","event_lang":"fre"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"Sous la direction de","lang":"fre","items":[]},"CONTENT_DESCRIPTOR":[{"content_nibble_level_1":"0x0","content_nibble_level_2":"0x0"}],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":7},"CA_IDENTIFIER_DESCRIPTOR":[],"SHORT_SMOOTHING_BUFFER_DESCRIPTOR":{"sb_leak_rate":"28"},"PRIVATE_DESCRIPTOR":[{"tag":"0xAB","token":"77"},{"tag":"0xAA","token":"88"}],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x03","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"fre"}]}', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"","event_text":"","event_lang":"eng"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"","lang":"eng","items":[]},"CONTENT_DESCRIPTOR":[],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":0},"CA_IDENTIFIER_DESCRIPTOR":[],"SHORT_SMOOTHING_BUFFER_DESCRIPTOR":{"sb_leak_rate":"13"},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x03","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"eng"},{"stream_content":"0x03","component_type":"0x10","set_component_tag":46,"text":"subtitle","lang":"eng"}]}', 1, 1449155124, 'arte.ts', 1, '232.0.6.18', 8200, 13, 0, 167, 'STARTED', '2016-03-04 20:06:25', 1, 1),
(2, 803, 2507, 'HD CSA 3 & TNT', 'Flux banc qualif', 'Banc qualif', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"CSA1 HD","event_text":"Fx CSA1 HD","event_lang":"fre"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"FD CSA1 HD","lang":"fre","items":[]},"CONTENT_DESCRIPTOR":[{"content_nibble_level_1":"0x9","content_nibble_level_2":"0x06"}],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":9},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x01","component_type":"0x02","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"fre"},{"stream_content":"0x03","component_type":"0x10","set_component_tag":46,"text":"subtitle","lang":"ger"}]}', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"test demo suivant","event_text":"","event_lang":"chi"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"","lang":"chi","items":[]},"CONTENT_DESCRIPTOR":[{"content_nibble_level_1":"0x3","content_nibble_level_2":"0x03"}],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":0},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x03","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"chi"},{"stream_content":"0x03","component_type":"0x10","set_component_tag":46,"text":"subtitle","lang":"chi"}]}', 1, 1452603174, 'france4.ts', 7, '232.0.6.7', 8200, 8, 0, 167, 'STARTED', '2016-03-04 20:06:31', 1, 1),
(3, 804, 2508, 'HD+ CSA 1 & TNT', 'Flux banc qualif', 'Banc qualif', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"CSA1 HD+ DOLBY VM","event_text":"Fx CSA1 HD+ DOLBY VM","event_lang":"fre"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"FD CSA1 HD+ DOLBY VM","lang":"fre","items":[]},"CONTENT_DESCRIPTOR":[{"content_nibble_level_1":"0x7","content_nibble_level_2":"0x09"}],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":0},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x0B","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"eng"},{"stream_content":"0x04","component_type":"0x75","set_component_tag":46,"text":"audio","lang":"ita"}]}', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"test243","event_text":"test2","event_lang":"chi"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"test","lang":"chi","items":[]},"CONTENT_DESCRIPTOR":[{"content_nibble_level_1":"0x3","content_nibble_level_2":"0x03"}],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":0},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x03","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"chi"},{"stream_content":"0x03","component_type":"0x10","set_component_tag":46,"text":"subtitle","lang":"chi"}]}', 1, 1452678376, 'arteHD+.ts', 5, '232.0.6.8', 8200, 9, 0, 167, 'STARTED', '2016-03-04 20:06:37', 1, 1),
(4, 808, 2501, 'SD CSA 1', 'Flux banc qualif', 'Banc qualif', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"CSA1 SD AD HOH","event_text":"Fx CSA1 SD AD HOH","event_lang":"fre"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"FD CSA1 SD AD HOH","lang":"fre","items":[]},"CONTENT_DESCRIPTOR":[{"content_nibble_level_1":"0x5","content_nibble_level_2":"0x03"}],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":0},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x03","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x40","set_component_tag":46,"text":"audio","lang":"fre"},{"stream_content":"0x03","component_type":"0x20","set_component_tag":46,"text":"subtitle","lang":"eng"}]}', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"Following Event","event_text":"Following Event","event_lang":"chi"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"test","lang":"ita","items":[]},"CONTENT_DESCRIPTOR":[{"content_nibble_level_1":"0x2","content_nibble_level_2":"0x03"}],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":0},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x03","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"chi"},{"stream_content":"0x03","component_type":"0x10","set_component_tag":46,"text":"subtitle","lang":"rus"}]}', 1, 1452602548, 'france5_sd.ts', 6, '232.0.6.1', 8200, 2, 0, 167, 'STARTED', '2016-03-04 20:06:42', 1, 1),
(5, 809, 2502, 'HD CSA 2', 'Flux banc qualif', 'Banc qualif', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"CSA2 HD HOH DOLBY","event_text":"Fx CSA2 HD HOH DOLBY","event_lang":"fre"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"FD CSA2 HD HOH DOLBY","lang":"fre","items":[]},"CONTENT_DESCRIPTOR":[{"content_nibble_level_1":"0x2","content_nibble_level_2":"0x02"}],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":7},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x0B","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x04","component_type":"0x75","set_component_tag":46,"text":"audio","lang":"eng"},{"stream_content":"0x03","component_type":"0x20","set_component_tag":46,"text":"subtitle","lang":"fre"}]}', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"Following Event - Following Event - Following Even","event_text":"Following Event","event_lang":"bre"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"test","lang":"bre","items":[]},"CONTENT_DESCRIPTOR":[{"content_nibble_level_1":"0x4","content_nibble_level_2":"0x09"}],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":0},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x03","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"bre"},{"stream_content":"0x03","component_type":"0x10","set_component_tag":46,"text":"subtitle","lang":"bre"}]}', 1, 1452602697, 'D8_sd.ts', 27, '232.0.6.2', 8200, 3, 0, 167, 'STARTED', '2016-03-04 20:06:47', 1, 1),
(6, 810, 2503, 'SD CSA 3', 'Flux banc qualif', 'Banc qualif', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"CSA3 SD AD","event_text":"Fx CSA3 SD AD","event_lang":"fre"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"FD CSA3 SD AD","lang":"fre","items":[]},"CONTENT_DESCRIPTOR":[{"content_nibble_level_1":"0x7","content_nibble_level_2":"0x03"}],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":9},"PRIVATE_DESCRIPTOR":[{"tag":"0xAA","token":"10"}],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x01","component_type":"0x01","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"fre"},{"stream_content":"0x06","component_type":"0x40","set_component_tag":46,"text":"audio","lang":"eng"}]}', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"Following EVENT - SOFT Team","event_text":"test2","event_lang":"bre"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"test","lang":"bre","items":[]},"CONTENT_DESCRIPTOR":[{"content_nibble_level_1":"0x3","content_nibble_level_2":"0x03"}],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":0},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x03","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"bre"},{"stream_content":"0x03","component_type":"0x10","set_component_tag":46,"text":"subtitle","lang":"bre"}]}', 1, 1452602890, 'france2.ts', 3, '232.0.6.3', 8200, 4, 0, 167, 'STARTED', '2016-03-04 20:06:53', 1, 1),
(7, 811, 2504, 'HD CSA 4', 'Flux banc qualif', 'Banc qualif', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"CSA4 HD DTS VoVF","event_text":"Fx CSA4 HD DTS VoVF","event_lang":"fre"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"FD CSA4 HD DTS VoVF","lang":"fre","items":[]},"CONTENT_DESCRIPTOR":[{"content_nibble_level_1":"0x9","content_nibble_level_2":"0x03"}],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":13},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x01","component_type":"0x09","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x07","component_type":"0x7F","set_component_tag":46,"text":"audio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"ger"}]}', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"test demo suivant","event_text":"","event_lang":"chi"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"","lang":"chi","items":[]},"CONTENT_DESCRIPTOR":[{"content_nibble_level_1":"0x3","content_nibble_level_2":"0x03"}],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":0},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x03","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"chi"},{"stream_content":"0x03","component_type":"0x10","set_component_tag":46,"text":"subtitle","lang":"chi"}]}', 1, 1453989936, 'd8_hd.ts', 35, '232.0.6.4', 8200, 5, 0, 167, 'STARTED', '2016-03-04 20:06:58', 1, 1),
(8, 812, 2505, 'HD CSA1 - CSA5 XXL', 'Flux IP HD CSA1 CSA5 XXL', 'Banc qualif', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"IP CSA1 CSA5 XXL HD 16/9","event_text":"Flux IP CSA1 CSA5 XX","event_lang":"fre"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"Full description Flu","lang":"fre","items":[]},"CONTENT_DESCRIPTOR":[{"content_nibble_level_1":"0x6","content_nibble_level_2":"0x03"}],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":15},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x03","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"fre"},{"stream_content":"0x03","component_type":"0x10","set_component_tag":46,"text":"subtitle","lang":"eng"}]}', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"test241","event_text":"test2","event_lang":"chi"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"test","lang":"chi","items":[]},"CONTENT_DESCRIPTOR":[{"content_nibble_level_1":"0x7","content_nibble_level_2":"0x01"}],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":0},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x03","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"chi"},{"stream_content":"0x03","component_type":"0x10","set_component_tag":46,"text":"subtitle","lang":"chi"}]}', 1, 1452612326, 'csa1_csa5_xxl.ts', 9, '232.0.6.5', 8200, 6, 0, 167, 'STARTED', '2016-03-04 20:07:03', 1, 1),
(9, 813, 2506, 'HD CSA 5 XXL', 'Flux IP HD CSA5 XXL', 'Banc qualif', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"IP CSA5 PENTHOUSE HD 16/9","event_text":"Flux IP CSA5 PENTHOU","event_lang":"fre"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"Full description Flu","lang":"fre","items":[]},"CONTENT_DESCRIPTOR":[{"content_nibble_level_1":"0x8","content_nibble_level_2":"0x01"}],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":15},"CA_IDENTIFIER_DESCRIPTOR":[],"SHORT_SMOOTHING_BUFFER_DESCRIPTOR":{"sb_leak_rate":"10"},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x0B","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"eng"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"fre"}]}', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"test242","event_text":"test2","event_lang":"chi"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"test","lang":"chi","items":[]},"CONTENT_DESCRIPTOR":[],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":0},"CA_IDENTIFIER_DESCRIPTOR":[],"SHORT_SMOOTHING_BUFFER_DESCRIPTOR":{"sb_leak_rate":"10"},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x03","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"chi"},{"stream_content":"0x03","component_type":"0x10","set_component_tag":46,"text":"subtitle","lang":"chi"}]}', 1, 1452867050, 'csa5_xxl.ts', 10, '232.0.6.6', 8200, 7, 0, 167, 'STARTED', '2016-03-04 20:07:08', 1, 0),
(10, 815, 2513, 'HD CSA1 - CSA 5 OCS CHOC', 'Flux IP HD CSA1 CSA5 OCS CHOC', 'Banc qualif', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"IP CSA1 CSA5 OCS CHOC HD 16/9","event_text":"Flux IP CSA1 CSA5 OC","event_lang":"fre"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"Full description Flu","lang":"fre","items":[]},"CONTENT_DESCRIPTOR":[{"content_nibble_level_1":"0x8","content_nibble_level_2":"0x01"}],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":15},"CA_IDENTIFIER_DESCRIPTOR":[],"SHORT_SMOOTHING_BUFFER_DESCRIPTOR":{"sb_leak_rate":"10"},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x0B","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"eng"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"fre"}]}', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"test242","event_text":"test2","event_lang":"chi"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"test","lang":"chi","items":[]},"CONTENT_DESCRIPTOR":[],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":0},"CA_IDENTIFIER_DESCRIPTOR":[],"SHORT_SMOOTHING_BUFFER_DESCRIPTOR":{"sb_leak_rate":"10"},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x03","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"chi"},{"stream_content":"0x03","component_type":"0x10","set_component_tag":46,"text":"subtitle","lang":"chi"}]}', 1, 1449564640, 'csa4_csa5_ocs_choc.ts', 11, '232.0.6.13', 8200, 20, 0, 167, 'STARTED', '2016-03-04 20:07:13', 1, 1),
(11, 816, 2514, 'HD CSA 5 OCS CHOC', 'Flux IP HD CSA5 OCS CHOC', 'Banc qualif', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"Ceci est un test","event_text":"Flux IP CSA5 OCS CHO","event_lang":"fre"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"Full description Flu","lang":"fre","items":[]},"CONTENT_DESCRIPTOR":[{"content_nibble_level_1":"0x8","content_nibble_level_2":"0x01"}],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":15},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x0B","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"eng"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"fre"}]}', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"test242","event_text":"test2","event_lang":"chi"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"test","lang":"chi","items":[]},"CONTENT_DESCRIPTOR":[{"content_nibble_level_1":"0x3","content_nibble_level_2":"0x03"}],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":0},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x03","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"chi"},{"stream_content":"0x03","component_type":"0x10","set_component_tag":46,"text":"subtitle","lang":"chi"}]}', 1, 1452867108, 'csa5_ocs_choc.ts', 12, '232.0.6.14', 8200, 21, 0, 167, 'STARTED', '2016-03-04 20:07:18', 1, 1),
(12, 817, 2515, 'HD CSA1 -  CSA4 OCS CHOC', 'Flux IP HD CSA1 CSA4 OCS CHOC', 'Banc qualif', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"IP CSA1 CSA4 OCS CHOC HD 16/9","event_text":"Flux IP CSA1 CSA4 OC","event_lang":"fre"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"Full description Flu","lang":"fre","items":[]},"CONTENT_DESCRIPTOR":[{"content_nibble_level_1":"0x8","content_nibble_level_2":"0x01"}],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":13},"CA_IDENTIFIER_DESCRIPTOR":[],"SHORT_SMOOTHING_BUFFER_DESCRIPTOR":{"sb_leak_rate":"10"},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x0B","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"eng"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"fre"}]}', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"test242","event_text":"test2","event_lang":"chi"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"test","lang":"chi","items":[]},"CONTENT_DESCRIPTOR":[],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":0},"CA_IDENTIFIER_DESCRIPTOR":[],"SHORT_SMOOTHING_BUFFER_DESCRIPTOR":{"sb_leak_rate":"10"},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x03","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"chi"},{"stream_content":"0x03","component_type":"0x10","set_component_tag":46,"text":"subtitle","lang":"chi"}]}', 1, 1449564656, 'csa1_csa4_ocs_choc.ts', 13, '232.0.6.15', 8200, 22, 0, 167, 'STARTED', '2016-03-04 20:07:24', 1, 1),
(13, 818, 2516, 'HD CSA 4 ACTION', 'Flux IP HD CSA4 ACTION', 'Banc qualif', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"La chaîne de Dimitri","event_text":"Flux IP CSA4 ACTION ","event_lang":"fre"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"Full description Flu","lang":"fre","items":[]},"CONTENT_DESCRIPTOR":[{"content_nibble_level_1":"0x8","content_nibble_level_2":"0x01"}],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":13},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x0B","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x07","component_type":"0x7F","set_component_tag":46,"text":"audio","lang":"eng"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"fre"}]}', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"test242","event_text":"test2","event_lang":"chi"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"test","lang":"chi","items":[]},"CONTENT_DESCRIPTOR":[{"content_nibble_level_1":"0x7","content_nibble_level_2":"0x01"}],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":0},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x03","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"chi"},{"stream_content":"0x03","component_type":"0x10","set_component_tag":46,"text":"subtitle","lang":"chi"}]}', 1, 1452867855, 'csa4_ocs_choc.ts', 14, '232.0.6.16', 8200, 23, 0, 167, 'STARTED', '2016-03-04 20:07:29', 1, 1),
(14, 820, 2509, 'SD Mosaique 0', 'Flux IP SD Mosaique 0', 'Banc qualif', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"Mosaique 0","event_text":"Flux IP Mosaique 0 S","event_lang":"fre"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"Full description Flu","lang":"fre","items":[]},"CONTENT_DESCRIPTOR":[{"content_nibble_level_1":"0x6","content_nibble_level_2":"0x03"}],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":0},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x03","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x07","component_type":"0x7F","set_component_tag":46,"text":"audio","lang":"fre"},{"stream_content":"0x03","component_type":"0x20","set_component_tag":46,"text":"subtitle","lang":"eng"}]}', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"test241","event_text":"test2","event_lang":"chi"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"test","lang":"chi","items":[]},"CONTENT_DESCRIPTOR":[{"content_nibble_level_1":"0x7","content_nibble_level_2":"0x01"}],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":0},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x03","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"chi"},{"stream_content":"0x03","component_type":"0x10","set_component_tag":46,"text":"subtitle","lang":"chi"}]}', 1, 1452615877, 'mosaique.ts', 31, '232.0.6.9', 8200, 16, 0, 167, 'STARTED', '2016-03-04 20:07:34', 1, 1),
(15, 821, 2510, 'SD Mosaique 1', 'Flux IP SD Mosaique 1', 'Banc qualif', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"IP Mosaique 1 SD","event_text":"Flux IP Mosaique 1 S","event_lang":"fre"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"Full description Flu","lang":"fre","items":[]},"CONTENT_DESCRIPTOR":[{"content_nibble_level_1":"0x6","content_nibble_level_2":"0x03"}],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":0},"CA_IDENTIFIER_DESCRIPTOR":[],"SHORT_SMOOTHING_BUFFER_DESCRIPTOR":{"sb_leak_rate":"10"},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x03","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"fre"},{"stream_content":"0x03","component_type":"0x10","set_component_tag":46,"text":"subtitle","lang":"eng"}]}', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"test241","event_text":"test2","event_lang":"chi"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"test","lang":"chi","items":[]},"CONTENT_DESCRIPTOR":[{"content_nibble_level_1":"0x7","content_nibble_level_2":"0x01"}],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":0},"CA_IDENTIFIER_DESCRIPTOR":[],"SHORT_SMOOTHING_BUFFER_DESCRIPTOR":{"sb_leak_rate":"10"},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x03","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"chi"},{"stream_content":"0x03","component_type":"0x10","set_component_tag":46,"text":"subtitle","lang":"chi"}]}', 1, 1449564677, 'mosaique1.ts', 16, '232.0.6.10', 8200, 17, 0, 167, 'STARTED', '2016-03-04 20:07:39', 1, 1),
(16, 822, 2511, 'SD Mosaique 2', 'Flux IP SD Mosaique 2', 'Banc qualif', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"IP Mosaique 2 SD","event_text":"Flux IP Mosaique 2 S","event_lang":"fre"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"Full description Flu","lang":"fre","items":[]},"CONTENT_DESCRIPTOR":[{"content_nibble_level_1":"0x6","content_nibble_level_2":"0x03"}],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":0},"CA_IDENTIFIER_DESCRIPTOR":[],"SHORT_SMOOTHING_BUFFER_DESCRIPTOR":{"sb_leak_rate":"10"},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x03","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"fre"},{"stream_content":"0x03","component_type":"0x10","set_component_tag":46,"text":"subtitle","lang":"eng"}]}', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"test241","event_text":"test2","event_lang":"chi"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"test","lang":"chi","items":[]},"CONTENT_DESCRIPTOR":[{"content_nibble_level_1":"0x7","content_nibble_level_2":"0x01"}],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":0},"CA_IDENTIFIER_DESCRIPTOR":[],"SHORT_SMOOTHING_BUFFER_DESCRIPTOR":{"sb_leak_rate":"10"},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x03","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"chi"},{"stream_content":"0x03","component_type":"0x10","set_component_tag":46,"text":"subtitle","lang":"chi"}]}', 1, 1449564684, 'mosaique2.ts', 17, '232.0.6.11', 8200, 18, 0, 167, 'STARTED', '2016-03-04 20:07:44', 1, 1),
(17, 823, 2512, 'SD Mosaique 3', 'Flux 	IP SD Mosaique 3', 'Banc qualif', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"IP CSA1 CSA4 HD 16/9","event_text":"Flux IP CSA1 CSA4 HD","event_lang":"fre"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"Full description Flu","lang":"fre","items":[]},"CONTENT_DESCRIPTOR":[{"content_nibble_level_1":"0x6","content_nibble_level_2":"0x03"}],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":15},"CA_IDENTIFIER_DESCRIPTOR":[],"SHORT_SMOOTHING_BUFFER_DESCRIPTOR":{"sb_leak_rate":"10"},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x03","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"fre"},{"stream_content":"0x03","component_type":"0x10","set_component_tag":46,"text":"subtitle","lang":"eng"}]}', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"test241","event_text":"test2","event_lang":"chi"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"test","lang":"chi","items":[]},"CONTENT_DESCRIPTOR":[{"content_nibble_level_1":"0x7","content_nibble_level_2":"0x01"}],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":0},"CA_IDENTIFIER_DESCRIPTOR":[],"SHORT_SMOOTHING_BUFFER_DESCRIPTOR":{"sb_leak_rate":"10"},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x03","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"chi"},{"stream_content":"0x03","component_type":"0x10","set_component_tag":46,"text":"subtitle","lang":"chi"}]}', 1, 1456410316, 'mosaique3.ts', 18, '232.0.6.12', 8200, 19, 0, 167, 'STARTED', '2016-03-04 20:07:49', 1, 1),
(18, 824, 2517, 'SD Offre Canal +', 'Flux IP SD Offre Canal +', 'Banc qualif', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"IP SD Noir Blanc","event_text":"IP SD Noir Blanc","event_lang":"fre"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"Sous la direction d","lang":"fre","items":[]},"CONTENT_DESCRIPTOR":[{"content_nibble_level_1":"0x0","content_nibble_level_2":"0x0"}],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":0},"CA_IDENTIFIER_DESCRIPTOR":[],"SHORT_SMOOTHING_BUFFER_DESCRIPTOR":{"sb_leak_rate":"28"},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x03","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"fre"}]}', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"","event_text":"","event_lang":"eng"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"","lang":"eng","items":[]},"CONTENT_DESCRIPTOR":[],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":0},"CA_IDENTIFIER_DESCRIPTOR":[],"SHORT_SMOOTHING_BUFFER_DESCRIPTOR":{"sb_leak_rate":"13"},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x03","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"eng"},{"stream_content":"0x03","component_type":"0x10","set_component_tag":46,"text":"subtitle","lang":"eng"}]}', 1, 1453815972, 'canal_plus_non_crypte_crypte.ts', 34, '232.0.6.17', 8200, 24, 0, 167, 'STARTED', '2016-03-04 20:07:55', 1, 1),
(19, 801, 2519, 'SD CSA 1 &TNT', 'Flux banc qualif', 'Banc qualif', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"IP SD Noir Blanc","event_text":"IP SD Noir Blanc","event_lang":"fre"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"Sous la direction de","lang":"fre","items":[]},"CONTENT_DESCRIPTOR":[{"content_nibble_level_1":"0x0","content_nibble_level_2":"0x0"}],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":0},"CA_IDENTIFIER_DESCRIPTOR":[],"SHORT_SMOOTHING_BUFFER_DESCRIPTOR":{"sb_leak_rate":"28"},"PRIVATE_DESCRIPTOR":[{"tag":"0xAB","token":"77"},{"tag":"0xAA","token":"88"}],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x03","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"fre"}]}', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"","event_text":"","event_lang":"eng"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"","lang":"eng","items":[]},"CONTENT_DESCRIPTOR":[],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":0},"CA_IDENTIFIER_DESCRIPTOR":[],"SHORT_SMOOTHING_BUFFER_DESCRIPTOR":{"sb_leak_rate":"13"},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x03","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"eng"},{"stream_content":"0x03","component_type":"0x10","set_component_tag":46,"text":"subtitle","lang":"eng"}]}', 1, 1449224131, 'guilli_sd.ts', 26, '232.0.6.19', 8200, 25, 0, 167, 'STARTED', '2016-03-04 20:08:00', 1, 1),
(20, 830, 2530, 'SD CSA 1 AD', 'vrai audio description', 'Maxime', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"","event_text":"","event_lang":"fre"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"","lang":"fre","items":[]},"CONTENT_DESCRIPTOR":[],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":0},"CA_IDENTIFIER_DESCRIPTOR":[0],"SHORT_SMOOTHING_BUFFER_DESCRIPTOR":{"sb_leak_rate":"10"},"PRIVATE_DESCRIPTOR":[{"tag":"0xAA","token":""}],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x01","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"fre"},{"stream_content":"0x03","component_type":"0x10","set_component_tag":46,"text":"subtitle","lang":"fre"}]}', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"","event_text":"","event_lang":"fre"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"","lang":"fre","items":[]},"CONTENT_DESCRIPTOR":[],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":0},"CA_IDENTIFIER_DESCRIPTOR":[0],"SHORT_SMOOTHING_BUFFER_DESCRIPTOR":{"sb_leak_rate":"10"},"PRIVATE_DESCRIPTOR":[{"tag":"0xAA","token":""}],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x01","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"fre"},{"stream_content":"0x03","component_type":"0x10","set_component_tag":46,"text":"subtitle","lang":"fre"}]}', 1, 1449745037, 'france5_SD_AD.ts', 28, '232.0.6.30', 8200, 30, 0, 167, 'STARTED', '2016-03-04 20:08:05', 1, 1),
(21, 825, 2525, 'SD EIT extended desc', 'Flux IP SD EIT extended desc', 'Banc qualif', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"IP SD Noir Blanc","event_text":"IP SD Noir Blanc IP ","event_lang":"fre"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"Test extended eit","lang":"fre","items":[]},"CONTENT_DESCRIPTOR":[{"content_nibble_level_1":"0x0","content_nibble_level_2":"0x0"}],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":0},"CA_IDENTIFIER_DESCRIPTOR":[],"SHORT_SMOOTHING_BUFFER_DESCRIPTOR":{"sb_leak_rate":"28"},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x03","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"fre"}]}', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"","event_text":"","event_lang":"eng"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"","lang":"eng","items":[]},"CONTENT_DESCRIPTOR":[],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":0},"CA_IDENTIFIER_DESCRIPTOR":[],"SHORT_SMOOTHING_BUFFER_DESCRIPTOR":{"sb_leak_rate":"13"},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x03","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"eng"},{"stream_content":"0x03","component_type":"0x10","set_component_tag":46,"text":"subtitle","lang":"eng"}]}', 1, 1454576656, 'csa5_canal_plus_1.ts', 36, '232.0.6.25', 8200, 26, 0, 167, 'STARTED', '2016-03-04 20:08:10', 1, 1),
(22, 828, 2526, 'UHD 2160p h265', 'UHD 2160p', 'Banc qualif', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"IP UHD","event_text":"IP UHD","event_lang":"fre"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"Full description Flu","lang":"fre","items":[]},"CONTENT_DESCRIPTOR":[{"content_nibble_level_1":"0x6","content_nibble_level_2":"0x03"}],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":0},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x03","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"fre"},{"stream_content":"0x03","component_type":"0x10","set_component_tag":46,"text":"subtitle","lang":"eng"}]}', '{"SHORT_EVENT_DESCRIPTOR":{"event_name":"test241","event_text":"test2","event_lang":"chi"},"EXTENDED_EVENT_DESCRIPTOR":{"text":"test mosaique","lang":"chi","items":[]},"CONTENT_DESCRIPTOR":[{"content_nibble_level_1":"0x7","content_nibble_level_2":"0x01"}],"PARENTAL_RATING_DESCRIPTOR":{"country_code":"FRA","age":0},"PRIVATE_DESCRIPTOR":[],"COMPONENT_DESCRIPTOR":[{"stream_content":"0x05","component_type":"0x03","set_component_tag":46,"text":"aspect ratio","lang":"fre"},{"stream_content":"0x06","component_type":"0x03","set_component_tag":46,"text":"audio","lang":"chi"},{"stream_content":"0x03","component_type":"0x10","set_component_tag":46,"text":"subtitle","lang":"chi"}]}', 1, 1456414114, 'output_2160p_h265.ts', 39, '232.0.6.20', 8200, 32, 0, 167, 'STARTED', '2016-03-04 20:08:15', 1, 1);

-- --------------------------------------------------------

--
-- Table structure for table `video`
--

CREATE TABLE IF NOT EXISTS `video` (
  `idvideo` int(11) NOT NULL,
  `filename` varchar(255) CHARACTER SET utf8 NOT NULL,
  `description` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `color` tinyint(4) NOT NULL DEFAULT '1',
  `resolution` varchar(5) CHARACTER SET utf8 NOT NULL DEFAULT 'HD',
  `ocs` tinyint(4) NOT NULL DEFAULT '0',
  `csa5` tinyint(4) NOT NULL DEFAULT '0',
  `format` varchar(5) CHARACTER SET utf8 NOT NULL DEFAULT '16/9',
  `status` varchar(20) CHARACTER SET utf8 NOT NULL DEFAULT 'NEW',
  `enabled` tinyint(4) NOT NULL DEFAULT '1',
  `protected` tinyint(4) NOT NULL DEFAULT '1',
  `audio` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `subtitle` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `pmt` text CHARACTER SET utf8
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `video`
--

INSERT INTO `video` (`idvideo`, `filename`, `description`, `color`, `resolution`, `ocs`, `csa5`, `format`, `status`, `enabled`, `protected`, `audio`, `subtitle`, `pmt`) VALUES
(1, 'arte.ts', NULL, 0, 'SD', 0, 0, '4/3', 'READY', 1, 1, 'fra,eng,qad', 'fra,fra hoh', 'video: 0x1b - H.264/14496-10 video (MPEG-4/AVC)\naudio: 0x11 - 14496-3 Audio with LATM transport syntax (14496-3/AMD 1) - fra\naudio: 0x11 - 14496-3 Audio with LATM transport syntax (14496-3/AMD 1) - eng\naudio: 0x11 - 14496-3 Audio with LATM transport syntax (14496-3/AMD 1) - qad - [AD]\nsubtitle: 0x1 - Initial teletext page - fra\nsubtitle: 0x5 - Teletext subtitle page for hearing impaired people schedule page - fra - [HOH]\nsubtitle: 0x2 - Teletext subtitle page - fra\n'),
(3, 'france2.ts', NULL, 1, 'HD', 0, 0, '16/9', 'READY', 1, 1, 'fre,eng,qad', 'fre,fre hoh', 'video: 0x1b - H.264/14496-10 video (MPEG-4/AVC)\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - eng\naudio: 0x04 - 13818-3 audio (MPEG-2) - qad - [AD]\nsubtitle: 0x1 - Initial teletext page - fre\nsubtitle: 0x5 - Teletext subtitle page for hearing impaired people schedule page - fre - [HOH]\nsubtitle: 0x2 - Teletext subtitle page - fre\n'),
(5, 'arteHD+.ts', 'PMT audio DOLBY', 1, 'HD+', 0, 0, '16/9', 'READY', 1, 1, 'fre,qaa dolby,qad,ger', 'fre,fre hoh', 'video: 0x1b - H.264/14496-10 video (MPEG-4/AVC)\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x06 - 13818-1 PES private data - qaa - [DOLBY]\naudio: 0x04 - 13818-3 audio (MPEG-2) - qad - [AD]\naudio: 0x04 - 13818-3 audio (MPEG-2) - ger\nsubtitle: 0x1 - Initial teletext page - fre\nsubtitle: 0x5 - Teletext subtitle page for hearing impaired people schedule page - fre - [HOH]\nsubtitle: 0x2 - Teletext subtitle page - fre\n'),
(6, 'france5_sd.ts', NULL, 1, 'SD', 0, 0, '16/9', 'READY', 1, 1, 'fra,qad', 'fra,fra hoh', 'video: 0x1b - H.264/14496-10 video (MPEG-4/AVC)\naudio: 0x11 - 14496-3 Audio with LATM transport syntax (14496-3/AMD 1) - fra\naudio: 0x11 - 14496-3 Audio with LATM transport syntax (14496-3/AMD 1) - qad - [AD]\nsubtitle: 0x1 - Initial teletext page - fra\nsubtitle: 0x5 - Teletext subtitle page for hearing impaired people schedule page - fra - [HOH]\n'),
(7, 'france4.ts', NULL, 1, 'HD', 0, 0, '16/9', 'READY', 1, 1, 'fre,eng', 'fre,fre hoh', 'video: 0x1b - H.264/14496-10 video (MPEG-4/AVC)\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - eng\nsubtitle: 0x1 - Initial teletext page - fre\nsubtitle: 0x5 - Teletext subtitle page for hearing impaired people schedule page - fre - [HOH]\nsubtitle: 0x2 - Teletext subtitle page - fre\n'),
(9, 'csa1_csa5_xxl.ts', 'Bouquet CSA5', 1, 'SD', 0, 1, '16/9', 'READY', 1, 1, 'fra', '', 'video: 0x1b - H.264/14496-10 video (MPEG-4/AVC)\naudio: 0x04 - 13818-3 audio (MPEG-2) - fra\n'),
(10, 'csa5_xxl.ts', 'Bouquet CSA5', 1, 'HD', 0, 1, '16/9', 'READY', 1, 1, 'fra', '', 'video: 0x1b - H.264/14496-10 video (MPEG-4/AVC)\naudio: 0x04 - 13818-3 audio (MPEG-2) - fra\n'),
(11, 'csa4_csa5_ocs_choc.ts', 'Bouquet OCS CSA5', 1, 'HD', 1, 1, '16/9', 'READY', 1, 1, 'fra,eng', 'fra,fra hoh', 'video: 0x1b - H.264/14496-10 video (MPEG-4/AVC)\naudio: 0x11 - 14496-3 Audio with LATM transport syntax (14496-3/AMD 1) - fra\naudio: 0x11 - 14496-3 Audio with LATM transport syntax (14496-3/AMD 1) - eng\nsubtitle: 0x1 - Initial teletext page - fra\nsubtitle: 0x5 - Teletext subtitle page for hearing impaired people schedule page - fra - [HOH]\nsubtitle: 0x2 - Teletext subtitle page - fra\n'),
(12, 'csa5_ocs_choc.ts', 'Bouquet OCS CSA5', 1, 'HD', 1, 1, '16/9', 'READY', 1, 1, 'fra,eng', 'fra,fra hoh', 'video: 0x1b - H.264/14496-10 video (MPEG-4/AVC)\naudio: 0x11 - 14496-3 Audio with LATM transport syntax (14496-3/AMD 1) - fra\naudio: 0x11 - 14496-3 Audio with LATM transport syntax (14496-3/AMD 1) - eng\nsubtitle: 0x1 - Initial teletext page - fra\nsubtitle: 0x5 - Teletext subtitle page for hearing impaired people schedule page - fra - [HOH]\nsubtitle: 0x2 - Teletext subtitle page - fra\n'),
(13, 'csa1_csa4_ocs_choc.ts', 'Bouquet OCS', 1, 'HD', 1, 0, '16/9', 'READY', 1, 1, 'fra,eng', 'fra,fra hoh', 'video: 0x1b - H.264/14496-10 video (MPEG-4/AVC)\naudio: 0x11 - 14496-3 Audio with LATM transport syntax (14496-3/AMD 1) - fra\naudio: 0x11 - 14496-3 Audio with LATM transport syntax (14496-3/AMD 1) - eng\nsubtitle: 0x1 - Initial teletext page - fra\nsubtitle: 0x5 - Teletext subtitle page for hearing impaired people schedule page - fra - [HOH]\nsubtitle: 0x2 - Teletext subtitle page - fra\n'),
(14, 'csa4_ocs_choc.ts', 'Bouquet OCS', 1, 'SD', 1, 0, '16/9', 'READY', 1, 1, 'fra,eng', 'fra,fra hoh', 'video: 0x1b - H.264/14496-10 video (MPEG-4/AVC)\naudio: 0x11 - 14496-3 Audio with LATM transport syntax (14496-3/AMD 1) - fra\naudio: 0x11 - 14496-3 Audio with LATM transport syntax (14496-3/AMD 1) - eng\nsubtitle: 0x1 - Initial teletext page - fra\nsubtitle: 0x5 - Teletext subtitle page for hearing impaired people schedule page - fra - [HOH]\nsubtitle: 0x2 - Teletext subtitle page - fra\n'),
(16, 'mosaique1.ts', 'Flux pour 1ère page de la mosaic', 1, 'SD', 0, 0, '16/9', 'READY', 1, 1, 'fre', '', 'video: 0x1b - H.264/14496-10 video (MPEG-4/AVC)\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\n'),
(17, 'mosaique2.ts', 'Flux pour 2ème page de la mosaic', 1, 'SD', 0, 0, '16/9', 'READY', 1, 1, 'fre', '', 'video: 0x1b - H.264/14496-10 video (MPEG-4/AVC)\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\n'),
(18, 'mosaique3.ts', 'Flux pour 3ème page de la mosaic', 1, 'SD', 0, 0, '16/9', 'READY', 1, 1, 'fre', '', 'video: 0x1b - H.264/14496-10 video (MPEG-4/AVC)\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\n'),
(20, 'offres_canal_plus.ts', 'Les offres CANAL+ et CANALSAT', 1, 'SD', 0, 0, '16/9', 'READY', 1, 1, 'fra', '', 'video: 0x1b - H.264/14496-10 video (MPEG-4/AVC)\naudio: 0x04 - 13818-3 audio (MPEG-2) - fra\n'),
(26, 'guilli_sd.ts', '', 1, 'SD', 0, 0, '16/9', 'READY', 1, 1, 'fra', '', 'video: 0x1b - H.264/14496-10 video (MPEG-4/AVC)\naudio: 0x04 - 13818-3 audio (MPEG-2) - fra\n'),
(27, 'D8_sd.ts', '', 1, 'SD', 0, 0, '16/9', 'READY', 1, 1, 'fra,eng,qad', 'fra,fra hoh', 'video: 0x1b - H.264/14496-10 video (MPEG-4/AVC)\naudio: 0x04 - 13818-3 audio (MPEG-2) - fra\naudio: 0x04 - 13818-3 audio (MPEG-2) - eng\naudio: 0x03 - 11172-3 audio (MPEG-1) - qad - [AD]\nsubtitle: 0x2 - Teletext subtitle page - fra\nsubtitle: 0x5 - Teletext subtitle page for hearing impaired people schedule page - fra - [HOH]\n'),
(28, 'france5_SD_AD.ts', '', 1, 'SD', 0, 0, '16/9', 'READY', 1, 0, 'fra,qad', 'fra,fra hoh', 'video: 0x1b - H.264/14496-10 video (MPEG-4/AVC)\naudio: 0x11 - 14496-3 Audio with LATM transport syntax (14496-3/AMD 1) - fra\naudio: 0x11 - 14496-3 Audio with LATM transport syntax (14496-3/AMD 1) - qad - [AD]\nsubtitle: 0x1 - Initial teletext page - fra\nsubtitle: 0x5 - Teletext subtitle page for hearing impaired people schedule page - fra - [HOH]\n'),
(29, 'arte_sd.ts', '', 1, 'HD', 0, 0, '16/9', 'READY', 1, 1, 'fra,eng,qad', 'fra,fra hoh', 'video: 0x1b - H.264/14496-10 video (MPEG-4/AVC)\naudio: 0x11 - 14496-3 Audio with LATM transport syntax (14496-3/AMD 1) - fra\naudio: 0x11 - 14496-3 Audio with LATM transport syntax (14496-3/AMD 1) - eng\naudio: 0x11 - 14496-3 Audio with LATM transport syntax (14496-3/AMD 1) - qad - [AD]\nsubtitle: 0x1 - Initial teletext page - fra\nsubtitle: 0x5 - Teletext subtitle page for hearing impaired people schedule page - fra - [HOH]\nsubtitle: 0x2 - Teletext subtitle page - fra\n'),
(30, 'tf1_hd+_1.ts', '', 1, 'HD+', 0, 0, '16/9', 'READY', 1, 1, 'fra,qaa,qad', 'fra,fra hoh', 'video: 0x1b - H.264/14496-10 video (MPEG-4/AVC)\naudio: 0x11 - 14496-3 Audio with LATM transport syntax (14496-3/AMD 1) - fra\naudio: 0x11 - 14496-3 Audio with LATM transport syntax (14496-3/AMD 1) - qaa\naudio: 0x11 - 14496-3 Audio with LATM transport syntax (14496-3/AMD 1) - qad - [AD]\nsubtitle: 0x1 - Initial teletext page - fra\nsubtitle: 0x2 - Teletext subtitle page - fra\nsubtitle: 0x5 - Teletext subtitle page for hearing impaired people schedule page - fra - [HOH]\n'),
(31, 'mosaique.ts', '', 1, 'HD', 0, 0, '16/9', 'READY', 1, 1, 'fre', '', 'video: 0x1b - H.264/14496-10 video (MPEG-4/AVC)\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\naudio: 0x04 - 13818-3 audio (MPEG-2) - fre\n'),
(34, 'canal_plus_non_crypte_crypte.ts', '', 1, 'HD', 0, 0, '16/9', 'READY', 1, 1, 'fra,eng,qad', 'fra,fra hoh', 'video: 0x1b - H.264/14496-10 video (MPEG-4/AVC)\naudio: 0x04 - 13818-3 audio (MPEG-2) - fra\naudio: 0x04 - 13818-3 audio (MPEG-2) - eng\naudio: 0x03 - 11172-3 audio (MPEG-1) - qad - [AD]\nsubtitle: 0x2 - Teletext subtitle page - fra\nsubtitle: 0x5 - Teletext subtitle page for hearing impaired people schedule page - fra - [HOH]\n'),
(35, 'd8_hd.ts', '', 1, 'HD', 0, 0, '16/9', 'READY', 1, 1, 'fra,eng,qad', 'fra,fra hoh', 'video: 0x1b - H.264/14496-10 video (MPEG-4/AVC)\naudio: 0x04 - 13818-3 audio (MPEG-2) - fra\naudio: 0x04 - 13818-3 audio (MPEG-2) - eng\naudio: 0x03 - 11172-3 audio (MPEG-1) - qad - [AD]\nsubtitle: 0x2 - Teletext subtitle page - fra\nsubtitle: 0x5 - Teletext subtitle page for hearing impaired people schedule page - fra - [HOH]\n'),
(36, 'csa5_canal_plus_2.ts', '', 1, 'HD', 0, 0, '16/9', 'READY', 1, 1, 'fra,eng,qad', 'fra,fra hoh', 'video: 0x1b - H.264/14496-10 video (MPEG-4/AVC)\naudio: 0x04 - 13818-3 audio (MPEG-2) - fra\naudio: 0x04 - 13818-3 audio (MPEG-2) - eng\naudio: 0x03 - 11172-3 audio (MPEG-1) - qad - [AD]\nsubtitle: 0x2 - Teletext subtitle page - fra\nsubtitle: 0x5 - Teletext subtitle page for hearing impaired people schedule page - fra - [HOH]\n'),
(39, 'output_2160p_h265.ts', '', 1, 'UHD', 0, 0, '16/9', 'READY', 1, 1, 'und', '', 'audio: 0x0f - 13818-7 Audio with ADTS transport syntax - und\n'),
(40, 'Muse_4K_live_in_Rome.ts', '', 1, 'UHD', 0, 0, '16/9', 'READY', 1, 1, '', '', '');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `eit`
--
ALTER TABLE `eit`
 ADD PRIMARY KEY (`ideit`), ADD UNIQUE KEY `address_UNIQUE` (`address`);

--
-- Indexes for table `video`
--
ALTER TABLE `video`
 ADD PRIMARY KEY (`idvideo`), ADD UNIQUE KEY `filename` (`filename`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
