---
# This playbook install common tools and configure Orange proxy and time

- name: apply common configuration to all nodes
  hosts: qualif
  remote_user: qualif
  become_user: root
  become_method: su

  roles:
    - common
    - proxy
    - time
