---
# This playbook will install stream-manager


#########################
# Get latest standalone #
#########################

- name: Remove existing standalone directory
  file: >
    path={{ standalone_path }}
    state=absent
  become: yes

- name: Create standalone directory
  file: >
    path={{ standalone_path }}
    state=directory
    owner=qualif
    group=qualif
  become: yes

- name: Download and extract standalone
  unarchive: >
    src={{ standalone_url }}
    dest={{ standalone_path }}
    owner=qualif
    group=qualif
    copy=no
  become: yes


###############################
# Enable and start standalone #
###############################

- name: Create standalone service
  template: >
    src={{ standalone_service_template }}
    dest={{ standalone_service_path }}
  become: yes

- name: Stop and disable existing standalone service
  service: >
    name={{ standalone_service_name }}
    state=stopped
    enabled=no
  become: yes

- name: Enable standalone service
  service: >
    name={{ standalone_service_name }}
    state=started
    enabled=yes
  become: yes
