---
# This playbook will install stream-manager

##################
# stream-manager #
##################

# TODO when open source
# - clone github streammanager
# - compile war with database config
# - copy war into tomcat8 webapps folder


#######################
# multicat-supervisor #
#######################

- name: Remove existing multicat-supervisor directory
  file: path={{ multicat_supervisor_path }} state=absent
  become: yes

- name: Create multicat-supervisor src directory
  file: path={{ multicat_supervisor_src_dir_path }} state=directory
  become: yes

- name: Clone multicat-supervisor repository
  git: >
    repo={{ multicat_supervisor_url }}
    dest={{ multicat_supervisor_src_path }}
  become: yes


#############
# bitstream #
#############

- name: Get bitstream library (get_url don't work with https)
  command: "wget {{ bitstream_url }} -O {{ multicat_supervisor_src_dir_path }}/{{ bitstream_archive_name }}"
  become: yes

- name: Creates bitstream directory
  file: path={{ bitstream_src_path }} state=directory
  become: yes

- name: Extract bitstream library
  unarchive: >
    src={{ multicat_supervisor_src_dir_path }}/{{ bitstream_archive_name }}
    dest={{ multicat_supervisor_src_dir_path }}
    copy=no
  become: yes

- name: Install bitstream library
  command: chdir={{ bitstream_src_path }} {{ item }}
  with_items:
    - /usr/bin/make install
  become: yes


##########
# Config #
##########

- name: Config stream manager database host
  replace: >
    dest={{ multicat_supervisor_src_path }}/{{ multicat_supervisor_config_file }} regexp='^host=$'
    replace='host={{ database_host }}'
  become: yes

- name: Config stream manager database username
  replace: >
    dest={{ multicat_supervisor_src_path }}/{{ multicat_supervisor_config_file }} regexp='^username=$'
    replace='username={{ database_username }}'
  become: yes

- name: Config streammanager database password
  replace: >
    dest={{ multicat_supervisor_src_path }}/{{ multicat_supervisor_config_file }} regexp='^password=$'
    replace='password={{ database_password }}'
  become: yes

- name: Config stream manager database name
  replace: >
    dest={{ multicat_supervisor_src_path }}/{{ multicat_supervisor_config_file }} regexp='^database=$'
    replace='database={{ database_name }}'
  become: yes

- name: Config stream manager database ttl
  replace: >
    dest={{ multicat_supervisor_src_path }}/{{ multicat_supervisor_config_file }} regexp='^ttl=$'
    replace='ttl={{ network_ttl }}'
  become: yes


#########
# Start #
#########

- name: Compile and install multicat-supervisor
  command: chdir={{ multicat_supervisor_src_path }} {{ item }}
  with_items:
    - /usr/bin/make clean
    - /usr/bin/make install
  become: yes

- name: Create videos multicat directory
  file: >
    path={{ multicat_supervisor_videos_path }}
    state=directory
  become: yes

- name: Restore videos multicat directory from nas
  command: cp -R {{ multicat_supervisor_videos_nas_path }} {{ multicat_supervisor_path }}
  become: yes

- name: Create multicat-supervisor service
  template: >
    src={{ multicat_supervisor_service_template }}
    dest={{ multicat_supervisor_service_path }}
  become: yes

- name: Stop and disable existing multicat-supervisor service
  service: >
    name={{ multicat_supervisor_service_name }}
    state=stopped
    enabled=no
  become: yes

- name: Enable and start multicat-supervisor service
  service: >
    name={{ multicat_supervisor_service_name }}
    state=started
    enabled=yes
  become: yes
