---
# This playbook will configure some tools with proxy

#######
# env #
#######

# This playbook will configure Orange proxy

- name: Config environment proxy
  template: >
    src={{ environment_config_template }}
    dest={{ environment_config_file }}
  become: yes


#######
# apt #
#######

- name: Config apt proxy
  template: >
    src={{ apt_config_template }}
    dest={{ apt_config_file }}
  become: yes


#########
# cntlm #
#########

- name: Setting up cntlm configuration
  template: >
    src={{ cntlm_config_template }}
    dest={{ cntlm_config_file }}
  become: yes

- name: Restart the cntlm service
  service: >
    name=cntlm
    state=restarted
    sleep=3
  become: yes


#######
# git #
#######

- name: Add http git proxy
  command: "{{ git_config_http_command }}"

- name: Add https git proxy
  command: "{{ git_config_https_command }}"


########
# wget #
########

- name: Config wget proxy
  template: >
    src={{ wgetrc_template }}
    dest=/home/{{ qualif_user_name }}/{{ wgetrc_file }}


#########
# maven #
#########

- name: Remove old maven proxy config
  lineinfile: >
    dest={{ maven_settings_file }}
    regexp="{{ maven_proxy_tag }}"
    state=absent
  become: yes

- name: Config maven proxy
  lineinfile: >
    dest={{ maven_settings_file }}
    insertafter="{{ maven_proxies_tag }}"
    line="{{ item.line }}"
    state=present
  with_items:
    - "{{ maven_proxy }}"
  become: yes
