---
# This playbook will enable phpmyadmin

##########
# Config #
##########

- name: Create symlink for phpmyadmin
  file: >
    src={{ phpmyadmin_src_path }}
    dest={{ phpmyadmin_dest_path }}
    state=link
  become: yes
