---

#######
# apt #
#######

apt_config_template: apt.conf.j2
apt_config_file: /etc/apt/apt.conf.d/01proxy

###############
# environment #
###############

environment_config_template: environment.conf.j2
environment_config_file: /etc/environment

#########
# cntlm #
#########

deb_cntlm_package: cntlm_0.92.3-1_amd64.deb

cntlm_config_template: cntlm.conf.j2
cntlm_config_file: /etc/cntlm.conf

cntlm_username: skwp5790
cntlm_domain: ad.francetelecom.fr

cntlm_pass_lm: C104B7E7834BA39ADA5F4423AA8761A5
cntlm_pass_nt: 31E9A4FC4EE14B6BDB129B67876AF24D
cntlm_pass_ntlm: 5B09C6A7F62653ECF9BDA98C37C6810A

cntlm_proxies:
  - { ip: proxy-tls.toulouse.francetelecom.fr, port: 8080 }
  - { ip: proxy, port: 8080 }
  - { ip: proxybkp, port: 8080 }

cntlm_no_proxy: "localhost, 127.0.0.*, 10.*, 192.168.*"

cntlm_listen_address: localhost
cntlm_listen_port: 3128
