---
# This playbook will create cron jobs


- name: Add cron job for root user
  cron: >
    name="{{ item.name }}"
    minute="{{ item.minute }}"
    hour="{{ item.hour }}"
    job="{{ item.job }}"
    user="root"
  with_items:
    "{{ cron_jobs }}"
  become: yes
