---
# This playbook will install serviio

###################
# Install serviio #
###################

- name: Remove existing serviio directory
  file: >
    path={{ serviio_path }}
    state=absent
  become: yes

- name: Download and extract serviio
  unarchive: >
    src={{ serviio_url }}
    dest={{ lib_path }}
    copy=no
  become: yes

- name: Create serviio service
  template: >
    src={{ serviio_service_template }}
    dest={{ serviio_service_path }}
  become: yes

- name: Remove existing media serviio directory
  file: >
    path={{ seriio_media_path }}
    state=absent
  become: yes

- name: Create media serviio directory
  file: >
    path={{ seriio_media_path }}
    state=directory
  become: yes

- name: Restore servios directory from nas
  command: cp -R {{ seriio_media_nas_path }} {{ var_path }}
  when: restore_nas
  become: yes

- name: Stop and disable existing serviio service
  service: >
    name={{ serviio_service_name }}
    state=stopped
    enabled=no
  become: yes

- name: Enable and start serviio service
  service: >
    name={{ serviio_service_name }}
    state=started
    enabled=yes
  become: yes
