---
# This playbook will enable debug jenkins

################
# qualif bench #
################

- name: Restore qualif jenkins jobs config from nas
  command: rsync {{ rsync_options }} {{ qualif_jenkins_nas_path }}/ {{ jenkins_path }}/
  when: qualif_bench and restore_nas
  become: yes

- name: Restore qualif jenkins basic files from nas
  command: find {{ qualif_jenkins_nas_path }} -maxdepth 1 -type f -exec cp {} {{ jenkins_path }} \;
  when: qualif_bench and restore_nas
  become: yes

- name: Restore qualif jenkins plugins from nas
  command: ls /
  when: qualif_bench and restore_nas
  become: yes

- name: Restore qualif jenkins useful scripts from nas
  command: cp -R {{ item }} /home/{{ qualif_user_name }}/Bureau
  with_items:
    - "{{ qualif_nas_path }}/home/{{ qualif_user_name }}/Bureau/deployKarmaLite"
    - "{{ qualif_nas_path }}/home/{{ qualif_user_name }}/Bureau/deploy_standalone"
    - "{{ qualif_nas_path }}/home/{{ qualif_user_name }}/Bureau/deployRealase"
  when: qualif_bench and restore_nas
  become: yes

###############
# debug bench #
###############

- name: Restore debug jenkins jobs config from nas
  command: find {{ debug_jenkins_nas_path }} -maxdepth 1 -type f -exec cp {} {{ jenkins_path }} \;
  when: debug_bench and restore_nas
  become: yes

- name: Restore debug jenkins basic files from nas
  command: rsync {{ rsync_options }} {{ debug_jenkins_nas_path }}/ {{ jenkins_path }}/
  when: debug_bench and restore_nas
  become: yes

- name: Restore debug jenkins plugins from nas
  command: ls /
  when: debug_bench and restore_nas
  become: yes

- name: Restore debug jenkins useful scripts from nas
  command: cp -R {{ item }} /home/{{ qualif_user_name }}/Bureau
  with_items:
    - "{{ debug_nas_path }}/home/{{ qualif_user_name }}/Bureau/deployKarmaLite"
    - "{{ debug_nas_path }}/home/{{ qualif_user_name }}/Bureau/deploy_standalone"
    - "{{ debug_nas_path }}/home/{{ qualif_user_name }}/Bureau/deployRealase"
  when: debug_bench and restore_nas
  become: yes


#############
# all bench #
#############

- name: Restart the Jenkins service
  service: >
    name=jenkins
    state=restarted
    sleep=3
  become: yes
