---
# This playbook will enable debug jenkins

################
# qualif bench #
################

- name: Restore qualif jenkins jobs config from nas
  command: rsync {{ rsync_options }} {{ qualif_jenkins_nas_path }}/jobs/ {{ jenkins_path }}/jobs/
  when: qualif_bench and restore_nas
  become: yes

- name: Restore qualif jenkins basic files from nas
  command: find {{ qualif_jenkins_nas_path }} -maxdepth 1 -type f -exec cp {} {{ jenkins_path }} \;
  when: qualif_bench and restore_nas
  become: yes

- name: Restore qualif jenkins useful scripts from nas
  command: cp -R {{ qualif_nas_path }}/home/{{ user_name }}/Bureau/{{ item.folder }} /home/{{ user_name }}/Bureau
  with_items:
    - "{{ deploy_folders }}"
  when: qualif_bench and restore_nas
  become: yes

- name: Set qualif jenkins deploy folder permissions
  file: >
    path={{ qualif_nas_path }}/home/{{ user_name }}/Bureau/{{ item.folder }}
    owner=jenkins
    group=jenkins
    recurse=yes
    state=directory
  with_items:
    - "{{ deploy_folders }}"
  when: qualif_bench and restore_nas
  become: yes

- name: Restore qualif jenkins plugins from nas
  command: cp -R {{ qualif_jenkins_nas_path }}/plugins/{{ item.plugin }} {{ jenkins_path }}/plugins/
  with_items:
    - "{{ jenkins_plugins }}"
  when: qualif_bench and restore_nas
  become: yes

- name: Remove existing jenkins m2 repository directory
  file: >
    path={{ jenkins_m2_repo_path }}
    state=absent
  when: qualif_bench and restore_nas
  become: yes

- name: Restore jenkins m2 repository from nas
  command: cp -R {{ qualif_nas_path }}/home/{{ user_name }}/.m2 {{ jenkins_path }}
  when: qualif_bench and restore_nas
  become: yes

- name: Remove java 8 (avoid cascade-release job failure)
  apt: >
    name=oracle-java8-installer
    autoremove=yes
    state=absent
  when: qualif_bench
  become: yes

- name: Set jenkins service script
  template: >
    src={{ jenkins_service_template }}
    dest={{ jenkins_service_path }}
    mode=0751
  when: qualif_bench
  become: yes


###############
# debug bench #
###############

- name: Restore debug jenkins jobs config from nas
  command: rsync {{ rsync_options }} {{ debug_jenkins_nas_path }}/jobs/ {{ jenkins_path }}/jobs/
  when: debug_bench and restore_nas
  become: yes

- name: Restore debug jenkins basic files from nas
  command: find {{ debug_jenkins_nas_path }} -maxdepth 1 -type f -exec cp {} {{ jenkins_path }} \;
  when: debug_bench and restore_nas
  become: yes

- name: Restore debug jenkins useful scripts from nas
  command: cp -R {{ debug_nas_path }}/home/{{ user_name }}/Bureau/{{ item.folder }} /home/{{ user_name }}/Bureau
  with_items:
    - "{{ deploy_folders }}"
  when: debug_bench and restore_nas
  become: yes

- name: Set debug jenkins deploy folder permissions
  file: >
    path={{ debug_nas_path }}/home/{{ user_name }}/Bureau/{{ item.folder }}
    owner=jenkins
    group=jenkins
    recurse=yes
    state=directory
  with_items:
    - "{{ deploy_folders }}"
  when: debug_bench and restore_nas
  become: yes

- name: Restore debug jenkins plugins from nas
  command: cp -R {{ debug_jenkins_nas_path }}/plugins/{{ item.plugin }} {{ jenkins_path }}/plugins/
  with_items:
    - "{{ jenkins_plugins }}"
  when: debug_bench and restore_nas
  become: yes

- name: Restore debug jenkins themes from nas
  command: cp {{ debug_jenkins_nas_path }}/userContent/{{ item.theme }} {{ jenkins_path }}/userContent/
  with_items:
    - "{{ jenkins_themes }}"
  when: debug_bench and restore_nas
  become: yes

- name: Set jenkins service script
  template: >
    src={{ jenkins_service_template }}
    dest={{ jenkins_service_path }}
    mode=0751
  when: debug_bench
  become: yes


#############
# all bench #
#############

- name: Set xvfb script
  template: >
    src={{ jenkins_xvfb_template }}
    dest={{ jenkins_xvfb_path }}
    mode=0777
  become: yes

- name: Add xvfb script to startup
  command: >
    update-rc.d xvfb defaults
    chdir=/etc/init.d
  become: yes

- name: Clean existing user profile config
  command: >
    {{ jenkins_clean_profile_cmd }}
  become: yes

- name: Create workaround init jenkins directory
  file: >
    path={{ jenkins_workaround_path }}
    state=directory
  become: yes

- name: Copy workaround jenkins tests files
  copy: >
    src={{ item.file }}
    dest={{ jenkins_workaround_path }}
  with_items:
    - "{{ jenkins_workaround_files }}"
  become: yes

- name: Remove maven2 (not compatible with some jenkins jobs)
  apt: >
    name=maven2
    autoremove=yes
    state=absent
  become: yes

- name: Install maven (needed for some jenkins jobs)
  apt: >
    name=maven
    state=present
  become: yes

- name: Copy maven settings file
  copy: >
    src={{ maven_settings_file }}
    dest={{ maven_settings_path }}
  become: yes

- name: Set jenkins folder permissions
  file: >
    path={{ jenkins_path }}
    owner=jenkins
    group=jenkins
    recurse=yes
    state=directory
  become: yes

- name: Restart the Jenkins service
  service: >
    name=jenkins
    state=restarted
    sleep=3
  become: yes
