---
# This playbook will install main tools

########
# User #
########

- name: Install sudo (update cache first)
  apt: name=sudo state=present update_cache=yes
  become: yes

- name: Create qualif group
  group: name=qualif state=present
  become: yes

- name: Create qualif user
  user: >
    name=qualif
    shell=/bin/bash
    home=/home/{{ qualif_user_name }}
    groups=qualif,sudo
  become: yes

- name: Config sudoers
  lineinfile: >
    dest={{ sudoers_file }}
    insertafter=EOF
    line="{{ item.line }}"
    state=present
  with_items:
    - "{{ sudoers_list }}"
  become: yes


########
# Misc #
########

- name: Install misc tools
  apt: name={{item}} state=present
  with_items:
    - java-common
    - default-jre
    - default-jdk
    - zip
    - vim
    - curl
    - nload
  become: yes


#########
# Proxy #
#########

- name: Install cntlm
  apt: name=cntlm state=present
  become: yes


#######
# NTP #
#######

- name: Install ntp
  apt: name=ntp state=present
  become: yes


##############
# Subversion #
##############

- name: Install svn
  apt: name=subversion state=present
  become: yes

- name: Install git
  apt: name=git-core state=present
  become: yes


###########
# Jenkins #
###########

- name: Add Jenkins key
  apt_key: >
    url={{ jenkins_key_url }}
    state=present
  become: yes

- name: Add Jenkins apt repo (and update cache)
  apt_repository: >
    repo={{ jenkins_repo_url }}
    state=present
    update_cache=yes
  become: yes

- name: Install jenkins useful tools
  apt: >
    name={{ item }}
    force=yes
    state=present
  with_items:
    - xfonts-100dpi
    - xfonts-75dpi
    - xfonts-scalable
    - xfonts-cyrillic
    - xvfb
    - x11-apps
    - imagemagick
  become: yes

- name: Install Jenkins
  apt: >
    name=jenkins
    state=present
  become: yes


###############
# Web servers #
###############

- name: Install apache
  apt: name=apache2 state=present
  become: yes

- name: Install library apache svn
  apt: name=libapache2-svn state=present
  become: yes

- name: Install tomcat
  apt: name=tomcat8 state=present
  become: yes

- name: Change tomcat port to 8088 (avoid conflict with jenkins)
  replace: >
    dest={{ tomcat_path }}
    regexp="8080"
    replace="8088"
  become: yes

- name: Restart tomcat service
  service: >
    name=tomcat8
    state=restarted
    sleep=3
  become: yes


############
# Database #
############

- name: Install mysql-server
  apt: name={{ item }} state=present
  with_items:
   - mysql-server
   - python-mysqldb
  become: yes

- name: Install phpmyadmin
  apt: name=phpmyadmin state=present
  become: yes


############
# Streamer #
############

- name: Install dev package
  apt: name=build-essential state=present
  become: yes

- name: Install maven
  apt: name=maven2 state=present
  become: yes

- name: Install librairies for multicat-supervisor
  apt: name={{item}} state=present
  with_items:
    - libjson-c-dev
    - libmysqlclient-dev
    - libxml2-dev
  become: yes


########
# Java #
########

- name: Add java 8 source list
  template: >
    src={{ webupd8team_java_list_template }}
    dest={{ webupd8team_java_list_path }}
  become: yes

- name: Add java 8 key
  apt_key: >
    keyserver={{ webupd8team_java_key_url }}
    id={{ webupd8team_java_key_id }}
    state=present
  become: yes

- name: Accept java 8 license before install
  debconf: >
    name="{{ java_package_name }}"
    question="{{ java_license_question }}"
    value="true"
    vtype="select"
  become: yes

- name: Install java 8 (update cache first)
  apt: >
    name={{ java_package_name }}
    state=present
    force=yes
    update_cache=yes
  become: yes


###########
# Serviio #
###########

- name: Install libav tools
  apt: name=libav-tools state=present force=yes
  become: yes

- name: Add multimedia source list
  template: >
    src={{ multimedia_list_template }}
    dest={{ multimedia_list_path }}
  become: yes

- name: Install deb-multimedia-keyring
  apt: >
    name=deb-multimedia-keyring
    force=yes
    update_cache=yes
    state=present
  become: yes

- name: Install ffmpeg
  apt: >
    name=ffmpeg
    force=yes
    update_cache=yes
    state=present
  become: yes
