---
# This playbook will install main tools

########
# User #
########

- name: Install sudo (update cache first)
  apt: name=sudo state=present update_cache=yes
  become: yes

- name: Create qualif group
  group: name=qualif state=present
  become: yes

- name: Create qualif user
  user: >
    name=qualif
    shell=/bin/bash
    home=/home/qualif
    groups=qualif,sudo
    password={{ qualif_user_password }}
  become: yes


#########
# Proxy #
#########

- name: Install cntlm
  apt: name=cntlm state=present
  become: yes


########
# Time #
########

- name: Install ntp
  apt: name=ntp state=present
  become: yes


##############
# Subversion #
##############

- name: Install svn
  apt: name=subversion state=present
  become: yes

- name: Install git
  apt: name=git-core state=present
  become: yes


##############
# Web server #
##############

- name: Install apache
  apt: name=apache2 state=present
  become: yes

- name: Install library apache svn
  apt: name=libapache2-svn state=present
  become: yes

- name: Install tomcat
  apt: name=tomcat8 state=present
  become: yes


############
# Database #
############

- name: Install mysql-server
  apt: name={{ item }} state=present
  with_items:
   - mysql-server
   - python-mysqldb
  become: yes

- name: Install phpmyadmin
  apt: name=phpmyadmin state=present
  become: yes


##################
# Stream-manager #
##################

- name: Install dev package
  apt: name=build-essential state=present
  become: yes

- name: Install librairies for multicat-supervisor
  apt: name={{item}} state=installed
  with_items:
    - build-essential
    - libjson-c-dev
    - libmysqlclient-dev
    - libxml2-dev
  become: yes


##########
# Java 8 #
##########

- name: Add java 8 ppa
  template: >
    src={{ webupd8team_java_list_template }}
    dest={{ webupd8team_java_list_path }}
  become: yes

- name: Add java 8 keyserver
  apt_key: >
    keyserver=keyserver.ubuntu.com
    id=EEA14886
  become: yes

- name: Accept java 8 license before install
  debconf: >
    name='oracle-java8-installer'
    question='shared/accepted-oracle-license-v1-1'
    value='true'
    vtype='select'
  become: yes

- name: Install java 8 (update cache first)
  apt: >
    name=oracle-java8-installer
    state=present
    force=yes
    update_cache=yes
  become: yes


###########
# Jenkins #
###########

- name: Wget key
  get_url: url=https://jenkins-ci.org/debian/jenkins-ci.org.key dest=./jenkins-ci.org.key
  become: yes

- name: Add key
  command: apt-key add jenkins-ci.org.key
  become: yes

- name: Add repository
  command: sh -c 'echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list'
  become: yes

- name: Install Jenkins
  apt: name=jenkins state=present update_cache=yes
  become: yes


########
# Misc #
########

- name: Install misc tools
  apt: name={{item}} state=installed
  with_items:
    - zip
    - vim
  become: yes
