---
# This playbook contains common plays

##################
# User managment #
##################

- name: Install sudo (update cache first)
  apt: name=sudo state=present update_cache=yes
  become: yes

- name: Create qualif user in sudo group
  user: name=qualif comment="Qualif" group=sudo
  become: yes


###################
# Proxy managment #
###################

- name: Install cntlm
  apt: name=cntlm state=present
  become: yes

- name: Restart the cntlm service
  service: >
    name=cntlm
    state=started
    enabled=true
  become: yes


###################
# Time managment #
###################

- name: Set local timezone
  copy: >
    content={{ timezone }}
    dest=/etc/timezone
  become: yes

- name: Update tzdata
  command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata
  become: yes

- name: Install ntp
  apt: name=ntp state=present
  become: yes

- name: Setting up ntp servers configuration
  lineinfile: >
    dest=/etc/ntp.conf
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
  with_items:
    "{{ ntp_servers }}"
  become: yes

- name: Start the ntp service
  service: >
    name=ntp
    state=started
    enabled=true
  become: yes


#########################
# Subversion management #
#########################

- name: Install svn
  apt: name=subversion state=present
  become: yes

- name: Install git
  apt: name=git-core state=present
  become: yes
