---

apt_config_template: apt.conf.j2

rsync_options: -am --include='config.xml' --include='nextBuildNumber' --include='*/' --exclude='*'

jenkins_path: /var/lib/jenkins
jenkins_workaround_path: /var/lib/jenkins/workaround/init
jenkins_m2_repo_path: /var/lib/jenkins/.m2
qualif_nas_path: /mnt/nas/banc_qualif
debug_nas_path: /mnt/nas/banc_debug
debug_jenkins_nas_path: /mnt/nas/banc_debug/var/lib/jenkins
qualif_jenkins_nas_path: /mnt/nas/banc_qualif/var/lib/jenkins

jenkins_themes:
  - { theme: "jenkins_theme.css" }
  - { theme: "jenkins_theme.js" }

jenkins_plugins:
  - { plugin: "build-pipeline-plugin" }
  - { plugin: "build-pipeline-plugin.jpi" }
  - { plugin: "cascade-release" }
  - { plugin: "cascade-release.jpi" }
  - { plugin: "greenballs" }
  - { plugin: "greenballs.jpi" }
  - { plugin: "parameterized-trigger" }
  - { plugin: "parameterized-trigger.jpi" }
  - { plugin: "publish-over-ssh" }
  - { plugin: "publish-over-ssh.jpi" }
  - { plugin: "seleniumhq" }
  - { plugin: "seleniumhq.jpi" }
  - { plugin: "throttle-concurrents" }
  - { plugin: "throttle-concurrents.jpi" }
  - { plugin: "ws-cleanup" }
  - { plugin: "ws-cleanup.jpi" }
  - { plugin: "seleniumrc-plugin" }
  - { plugin: "seleniumrc-plugin.jpi" }

# List of deploy folders use by jenkins jobs
deploy_folders:
  - { folder: "deployKarmaLite" }
  - { folder: "deploy_standalone" }
  - { folder: "deployRealase" }

# List of jenkins init workaround files
jenkins_workaround_files:
  - { file: "INIT_JENKINS_TESTSUITE.html" }
  - { file: "init_jenkins.html" }

jenkins_xvfb_template: xvfb.j2
jenkins_xvfb_path: /etc/init.d/xvfb
jenkins_service_path: /etc/init.d/jenkins
jenkins_service_template: jenkins.j2

jenkins_display_port: 99

jenkins_clean_profile_cmd: "find /var/lib/jenkins/ -type f -exec sed -i 's/-firefoxProfileTemplate \\/var\\/lib\\/jenkins\\/firefox\\/ljhyckqd.Selenium/-singleWindow/g' {} \\;"

maven_settings_file: settings.xml
maven_settings_path: /etc/maven/settings.xml
