---

apt_config_template: apt.conf.j2

rsync_options: -am --include='config.xml' --include='firefox' --include='nextBuildNumber' --include='*/' --exclude='*'

jenkins_path: /var/lib/jenkins
qualif_nas_path: /mnt/nas/banc_qualif
debug_nas_path: /mnt/nas/banc_debug
debug_jenkins_nas_path: /mnt/nas/banc_debug/var/lib/jenkins
qualif_jenkins_nas_path: /mnt/nas/banc_qualif/var/lib/jenkins

jenkins_plugins:
  - { plugin: "build-pipeline-plugin" }
  - { plugin: "build-pipeline-plugin.jpi" }
  - { plugin: "greenballs" }
  - { plugin: "greenballs.jpi" }
  - { plugin: "parameterized-trigger" }
  - { plugin: "parameterized-trigger.jpi" }
  - { plugin: "publish-over-ssh" }
  - { plugin: "publish-over-ssh.jpi" }
  - { plugin: "seleniumhq" }
  - { plugin: "seleniumhq.jpi" }
  - { plugin: "throttle-concurrents" }
  - { plugin: "throttle-concurrents.jpi" }
  - { plugin: "ws-cleanup" }
  - { plugin: "ws-cleanup.jpi" }
  - { plugin: "seleniumrc-plugin" }
  - { plugin: "seleniumrc-plugin.jpi" }
