---
# This playbook will configure web servers

##########
# apache #
##########

- name: Enable mods
  command: a2enmod {{ item.mod }}
  with_items:
    "{{ apache_mods }}"
  become: yes

- name: Create apache ssl directory
  file: >
    path={{ apache_ssl_path }}
    state=directory
  become: yes

- name: Copy apache ssl certificate
  copy: >
    src={{ apache_ssl_certificate }}
    dest={{ apache_ssl_path }}
  become: yes

- name: Copy default conf files
  copy: >
    src={{ item.site }}
    dest={{ apache_sites_path }}
  with_items:
    "{{ apache_sites }}"
  become: yes

- name: Enable conf files
  command: a2ensite {{ item.site }}
  with_items:
    "{{ apache_sites }}"
  become: yes

- name: Restore www directory from nas
  command: cp -R {{ apache_www_nas_path }} {{ var_path }}
  when: restore_nas
  become: yes

- name: Set www-data www folder permissions
  file: >
    path={{ www_path }}/{{ item.folder }}
    owner=www-data
    group=www-data
    recurse=yes
    state=directory
  with_items:
    - "{{ www_data_folders }}"
  when: restore_nas
  become: yes

- name: Set qualif www folder permissions
  file: >
    path={{ www_path }}/{{ item.folder }}
    owner=qualif
    group=qualif
    recurse=yes
    state=directory
  with_items:
    - "{{ qualif_folders }}"
  when: restore_nas
  become: yes

- name: Set qualif www file permissions
  file: >
    path={{ www_path }}/{{ item.file }}
    owner=qualif
    group=qualif
    state=file
  with_items:
    - "{{ qualif_files }}"
  when: restore_nas
  become: yes

- name: Set qualif www dashboard permissions
  file: >
    src={{ www_path }}/test
    dest={{ www_path }}/dashboard
    owner=qualif
    group=qualif
    state=link
  when: restore_nas
  become: yes

- name: Set jenkins www folder permissions
  file: >
    path={{ www_path }}/{{ item.folder }}
    owner=jenkins
    group=jenkins
    recurse=yes
    state=directory
  with_items:
    - "{{ jenkins_folders }}"
  when: restore_nas
  become: yes

- name: Restart apache2 Service
  service: >
    name=apache2
    state=restarted
    sleep=3
  become: yes
