---
# This playbook will configure web servers

##########
# apache #
##########

- name: Enable mods
  command: a2enmod {{ item.mod }}
  with_items:
    "{{ apache_mods }}"
  become: yes

- name: Create apache ssl directory
  file: >
    path={{ apache_ssl_path }}
    state=directory
  become: yes

- name: Copy apache ssl certificate
  copy: >
    src={{ apache_ssl_certificate }}
    dest={{ apache_ssl_path }}
  become: yes

- name: Copy default conf files
  copy: >
    src={{ item.site }}
    dest={{ apache_sites_path }}
  with_items:
    "{{ apache_sites }}"
  become: yes

- name: Enable conf files
  command: a2ensite {{ item.site }}
  with_items:
    "{{ apache_sites }}"
  become: yes


################
# qualif bench #
################

- name: Restore qualif www directory from nas
  command: cp -R {{ qualif_www_nas_path }} {{ var_path }}
  when: qualif_bench and restore_nas
  become: yes

- name: Set qualif www folders permissions (www-data)
  file: >
    path={{ www_path }}/{{ item.folder }}
    owner=www-data
    group=www-data
    recurse=yes
    state=directory
  with_items:
    - "{{ www_data_folders }}"
  when: qualif_bench and restore_nas
  become: yes

- name: Set qualif www folders permissions (qualif)
  file: >
    path={{ www_path }}/{{ item.folder }}
    owner=qualif
    group=qualif
    recurse=yes
    state=directory
  with_items:
    - "{{ qualif_folders }}"
  when: qualif_bench and restore_nas
  become: yes

- name: Set qualif www files permissions (qualif)
  file: >
    path={{ www_path }}/{{ item.file }}
    owner=qualif
    group=qualif
    state=file
  with_items:
    - "{{ qualif_files }}"
  when: qualif_bench and restore_nas
  become: yes

- name: Set qualif www dashboard link permissions (qualif)
  file: >
    src={{ www_path }}/test
    dest={{ www_path }}/dashboard
    owner=qualif
    group=qualif
    state=link
  when: qualif_bench and restore_nas
  become: yes

- name: Set qualif www jenkins folder permissions (jenkins)
  file: >
    path={{ www_path }}/{{ item.folder }}
    owner=jenkins
    group=jenkins
    recurse=yes
    state=directory
  with_items:
    - "{{ jenkins_folders }}"
  when: qualif_bench and restore_nas
  become: yes


###############
# debug bench #
###############

- name: Restore debug www directory from nas
  command: cp -R {{ debug_www_nas_path }} {{ var_path }}
  when: debug_bench and restore_nas
  become: yes

- name: Set debug www dashboard link permissions (qualif)
  file: >
    src={{ www_path }}/test
    dest={{ www_path }}/dashboard
    owner=qualif
    group=qualif
    state=link
  when: debug_bench and restore_nas
  become: yes

- name: Set debug www test folder permissions (qualif)
  file: >
    path={{ www_path }}/test
    owner=qualif
    group=qualif
    recurse=yes
    state=directory
  when: debug_bench and restore_nas
  become: yes


#############
# all bench #
#############

- name: Restart apache2 Service
  service: >
    name=apache2
    state=restarted
    sleep=3
  become: yes
