---
# This playbook will mount nas

- name: Unmount existing nas
  mount: >
    name={{ nas_path }}
    src={{ nas_src }}
    fstype={{ nas_type }}
    opts={{ nas_options }}
    state=unmounted
  become: yes

- name: Remove existing nas entry
  mount: >
    name={{ nas_path }}
    src={{ nas_src }}
    fstype={{ nas_type }}
    opts={{ nas_options }}
    state=absent
  become: yes

- name: Create nas directory
  file: >
    path={{ nas_path }}
    state=directory
  become: yes

- name: Set nas mounting point
  mount: >
    name={{ nas_path }}
    src={{ nas_src }}
    fstype={{ nas_type }}
    opts={{ nas_options }}
    state=mounted
  become: yes


################
# qualif bench #
################

- name: Create qualif backup nas script directory
  file: >
    path={{ nas_backup_script_path }}
    state=directory
  when: qualif_bench
  become: yes

- name: Copy qualif nas backup script
  copy: >
    src={{ qualif_nas_backup_script }}
    dest={{ nas_backup_script_path }}/{{ nas_backup_script }}
    mode={{ nas_backup_script_rights }}
  when: qualif_bench
  become: yes


###############
# debug bench #
###############

- name: Create debug backup nas script directory
  file: >
    path={{ nas_backup_script_path }}
    state=directory
  when: debug_bench
  become: yes

- name: Copy debug nas backup script
  copy: >
    src={{ debug_nas_backup_script }}
    dest={{ nas_backup_script_path }}/{{ nas_backup_script }}
    mode={{ nas_backup_script_rights }}
  when: debug_bench
  become: yes
